image: node:24

# TODO: Use https://foundryvtt.com/article/package-release-api/ to automate new releases

cache:
  paths:
    - node_modules/

stages:
  - build
  - release

build:
  image: node:24
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y
    - apt-get install -y zip
    - rm -rf /var/lib/apt/lists/*
  script:
    - yarn install
    - yarn build
    - sed -i "s/CI_COMMIT_TAG/${CI_COMMIT_TAG}/g" dist/module.json
    - mv dist pf1-kineticist-enhancements
    - cp pf1-kineticist-enhancements/module.json ./
    - zip -q pf1-kineticist-enhancements.zip -r pf1-kineticist-enhancements/*
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file pf1-kineticist-enhancements.zip ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/pf1-kineticist-enhancements.zip
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file module.json ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/module.json
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file module.json ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/latest/module.json
  artifacts:
    paths:
      - pf1-kineticist-enhancements.zip
      - module.json

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  # Override before_script to avoid apt-get in this Alpine-based image
  before_script: []
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'pf1-kineticist-enhancements.zip'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/pf1-kineticist-enhancements.zip"
        - name: 'module.json'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/module.json"
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
