image: node:16.10.0

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build
  - release

build:
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  script:
    - yarn build
    - mv dist/* ./
    - sed -i 's/CI_COMMIT_TAG/$CI_COMMIT_TAG/g' module.json
  artifacts:
    paths:
      - lang/
      - module/
      - styles/
      - templates/
      - module.json
      - test.js

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
  #assets: # Optional, multiple asset links
  #  links:
  #    - name: 'asset1'

