image: node:16.10.0

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build
  - release

build:
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  script:
    - yarn build
    - mv dist/* ./
  artifacts:
    paths:
      - lang/
      - module/
      - styles/
      - templates/
      - module.json
      - test.js

release:
  image: node:16.10.0
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - sed -i 's/CI_COMMIT_TAG/$CI_COMMIT_TAG/g' module.json
    - npm install @semantic-release/gitlab
    - npx semantic-release


  #release:
  #  stage: release
  # only:
  #   - master
  #image: registry.gitlab.com/gitlab-org/release-cli:latest
  #release:
  #  tag_name: v${MAJOR}_${MINOR}_${REVISION}-alpha

