cache:
  paths:
    - node_modules/

stages:
  - build
  - release

image: node:16

build:
  image: node:16
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  script:
    - apt-get update && apt-get install -y zip
    - yarn install
    - yarn build
    - sed -i "s/VERSION/${CI_COMMIT_TAG}/g" dist/module.json
    - mv dist pf1-kineticist-enhancements
    - cp pf1-kineticist-enhancements/module.json ./
    - zip -q pf1-kineticist-enhancements.zip -r pf1-kineticist-enhancements/*
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file pf1-kineticist-enhancements.zip ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/pf1-kineticist-enhancements.zip
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file module.json ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/module.json
  artifacts:
    paths:
      - pf1-kineticist-enhancements.zip
      - module.json

# Generate manifest links, build dist directory
#version:
#  stage: build
#  before_script:
#    - *npm-ci
#    - apt-get --yes update
#    - apt-get --yes install jq
#  script:
#    - TEMP_MANIFEST=$(mktemp)
#    - |
#      jq '.version = $version | .url = $url | .manifest = $manifest | .download = $download' \
#      --arg version "${CI_COMMIT_TAG:1}" \
#      --arg url "$CI_PROJECT_URL" \
#      --arg manifest "$CI_PROJECT_URL/-/releases/permalink/latest/downloads/$PACKAGE_TYPE.json" \
#      --arg download "$CI_PROJECT_URL/-/releases/$CI_COMMIT_TAG/downloads/$PACKAGE_NAME.zip" \
#      public/$PACKAGE_TYPE.json > $TEMP_MANIFEST
#    - mv $TEMP_MANIFEST public/$PACKAGE_TYPE.json
#    - npm run build
#    - mv $BUILD_DIRECTORY $PACKAGE_NAME
#    expire_in: 1 week
#  # Run for version tags to prepare release, and for MRs to check successful build
#  rules:
#    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'


release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'pf1-kineticist-enhancements.zip'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/pf1-kineticist-enhancements.zip"
        - name: 'module.json'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/permalink/${CI_COMMIT_TAG}/module.json"
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    #- sed -i "s/$VERSION/$CI_COMMIT_TAG" filename
