{"com.linkedin.realtimefrontend.ClientConnection":{"personalTopics":["conversationsTopic","messageSeenReceiptsTopic","messagesTopic","replySuggestionTopicV2","tabBadgeUpdateTopic","typingIndicatorsTopic","invitationsTopic","inAppAlertsTopic","messageReactionSummariesTopic","socialPermissionsPersonalTopic","jobPostingPersonalTopic","messagingProgressIndicatorTopic","messagingDataSyncTopic","conversationDeletesTopic","messagingSecondaryPreviewBannerTopic","eventToastsTopic","realtimeSearchResultClustersTopic","generatedJobDescriptionsTopic","premiumGeneratedContentsTopic","coachStreamingResponsesTopic","conversationDraftsTopic","conversationDraftDeletesTopic","messageDraftsTopic","messageDraftDeletesTopic","messageStreamingUpdatesTopic"],"leftServerAt":1713826213973,"id":"7872cc39-e76a-4115-bdae-d9811f264ae8","serverProcessingTime":0}}

{"com.linkedin.realtimefrontend.DecoratedEvent":{"topic":"urn:li-realtime:tabBadgeUpdateTopic:urn:li-realtime:myself","leftServerAt":1713826216672,"id":"205c3146-9590-411d-83db-d1f5193d1bae","payload":{"data":{"value":{"badgingItemCounts":[{"count":1,"badgingItem":"MY_NETWORK","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":0,"badgingItem":"NURTURE","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":6,"badgingItem":"NOTIFICATIONS","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":0,"badgingItem":"MESSAGING","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"}],"$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.RealtimeBadgingItemCountsEvent"],"$type":"com.linkedin.voyager.dash.notifications.RealtimeBadgingItemCountsEvent"},"$type":"com.linkedin.restli.common.ActionResponse"},"included":[]},"trackingId":"Ê\u001EýÛä¿«Bíà +åÉ\u0012"}}

{"com.linkedin.realtimefrontend.DecoratedEvent":{"topic":"urn:li-realtime:tabBadgeUpdateTopic:urn:li-realtime:myself","leftServerAt":1713826217069,"id":"1097b696-e495-4dc8-958a-dd7e5c3527a7","payload":{"data":{"value":{"badgingItemCounts":[{"count":1,"badgingItem":"MY_NETWORK","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":0,"badgingItem":"NURTURE","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":6,"badgingItem":"NOTIFICATIONS","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":0,"badgingItem":"MESSAGING","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"}],"$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.RealtimeBadgingItemCountsEvent"],"$type":"com.linkedin.voyager.dash.notifications.RealtimeBadgingItemCountsEvent"},"$type":"com.linkedin.restli.common.ActionResponse"},"included":[]},"trackingId":"ÑÀ§dÜÑ¾µÅ\u0006/\u001BWÍ"}}

{"com.linkedin.realtimefrontend.Heartbeat":{}}

{"com.linkedin.realtimefrontend.Heartbeat":{}}

{"com.linkedin.realtimefrontend.Heartbeat":{}}

{"com.linkedin.realtimefrontend.DecoratedEvent":{"topic":"urn:li-realtime:tabBadgeUpdateTopic:urn:li-realtime:myself","leftServerAt":1713826267562,"id":"823e1c02-2496-494d-9476-e0730152b7e4","payload":{"data":{"value":{"badgingItemCounts":[{"count":0,"badgingItem":"NURTURE","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":1,"badgingItem":"MY_NETWORK","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":6,"badgingItem":"NOTIFICATIONS","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"},{"count":0,"badgingItem":"MESSAGING","$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.FullBadgingItemCount"],"$type":"com.linkedin.voyager.dash.notifications.BadgingItemCount"}],"$recipeTypes":["com.linkedin.voyager.dash.deco.notifications.RealtimeBadgingItemCountsEvent"],"$type":"com.linkedin.voyager.dash.notifications.RealtimeBadgingItemCountsEvent"},"$type":"com.linkedin.restli.common.ActionResponse"},"included":[]},"trackingId":"IC'ràÚtO\u001C\u000E"}}

{"com.linkedin.realtimefrontend.Heartbeat":{}}


{"com.linkedin.realtimefrontend.Heartbeat":{}}

